import Editor, { type Monaco } from "@monaco-editor/react";
import { useEffect, useState } from "react";
import JSZip from "jszip";
import { useRaincastStore } from "@/store/raincastStore";
import { useAIBuild } from "@/hooks/useAIBuild";
import { langForPath } from "@/services/codeExtractor";
import {
  FileExplorer,
  FileTabs,
  FilePathHeader,
} from "@/components/code/FileExplorer";
import { toast } from "sonner";

// Custom Monaco theme matching the spec.
function defineRaincastTheme(monaco: Monaco) {
  monaco.editor.defineTheme("raincast-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "546e7a", fontStyle: "italic" },
      { token: "keyword", foreground: "c792ea" },
      { token: "keyword.control", foreground: "c792ea" },
      { token: "string", foreground: "f78c6c" },
      { token: "string.quote", foreground: "f78c6c" },
      { token: "number", foreground: "f78c6c" },
      { token: "type", foreground: "82aaff" },
      { token: "type.identifier", foreground: "82aaff" },
      { token: "identifier", foreground: "c0c0d8" },
      { token: "tag", foreground: "89ddff" },
      { token: "tag.html", foreground: "89ddff" },
      { token: "delimiter.html", foreground: "89ddff" },
      { token: "attribute.name", foreground: "ffcb6b" },
      { token: "attribute.name.html", foreground: "ffcb6b" },
      { token: "attribute.value", foreground: "f78c6c" },
      { token: "metatag", foreground: "89ddff" },
      { token: "metatag.content.html", foreground: "f78c6c" },
      { token: "regexp", foreground: "f78c6c" },
      { token: "function", foreground: "82aaff" },
      { token: "variable", foreground: "c0c0d8" },
      { token: "variable.predefined", foreground: "82aaff" },
      { token: "variable.parameter", foreground: "ffcb6b" },
    ],
    colors: {
      "editor.background": "#111118",
      "editor.foreground": "#c0c0d8",
      "editorLineNumber.foreground": "#3a3a52",
      "editorLineNumber.activeForeground": "#8080a0",
      "editor.lineHighlightBackground": "#ffffff08",
      "editor.lineHighlightBorder": "#00000000",
      "editorCursor.foreground": "#00e5ff",
      "editor.selectionBackground": "#00e5ff22",
      "editor.inactiveSelectionBackground": "#ffffff10",
      "editorWidget.background": "#1a1a24",
      "editorWidget.border": "#1e1e2e",
      "editorIndentGuide.background": "#1e1e2e",
      "editorIndentGuide.activeBackground": "#2a2a3a",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#00000000",
      "scrollbarSlider.hoverBackground": "#00000000",
      "scrollbarSlider.activeBackground": "#00000000",
    },
  });
  monaco.editor.setTheme("raincast-dark");
}

export function CodeViewer() {
  const files = useRaincastStore((s) => s.files);
  const openTabs = useRaincastStore((s) => s.openTabs);
  const activeFile = useRaincastStore((s) => s.activeFile);
  const isBuilding = useRaincastStore((s) => s.isBuilding);
  const openFile = useRaincastStore((s) => s.openFile);
  const closeTab = useRaincastStore((s) => s.closeTab);
  const setActiveFile = useRaincastStore((s) => s.setActiveFile);
  const projectType = useRaincastStore((s) => s.projectType);
  const recentlyChanged = useRaincastStore((s) => s.recentlyChanged);
  const { regenerate } = useAIBuild();
  const [search, setSearch] = useState("");

  const paths = Object.keys(files);
  const currentPath = activeFile ?? openTabs[0] ?? null;
  const currentContent = currentPath ? files[currentPath] ?? "" : "";

  // Auto-scroll to bottom while streaming, top when build finishes.
  const [editorInstance, setEditorInstance] = useState<unknown | null>(null);
  useEffect(() => {
    if (!editorInstance || !currentPath) return;
    const ed = editorInstance as {
      getModel: () => { getLineCount: () => number } | null;
      revealLine: (n: number) => void;
      setPosition: (p: { lineNumber: number; column: number }) => void;
    };
    const model = ed.getModel();
    if (!model) return;
    if (isBuilding) {
      ed.revealLine(model.getLineCount());
    } else {
      ed.revealLine(1);
      ed.setPosition({ lineNumber: 1, column: 1 });
    }
  }, [currentContent, isBuilding, editorInstance, currentPath]);

  const copyCurrent = async () => {
    if (!currentPath) return;
    await navigator.clipboard.writeText(currentContent);
    toast.success(`Copied ${currentPath.split("/").pop()}`);
  };

  const downloadZip = async () => {
    if (paths.length === 0) return;
    const zip = new JSZip();
    for (const p of paths) zip.file(p, files[p]);
    zip.file(
      "README.md",
      `# Generated by RAINCAST\n\nProject type: ${projectType}\n\nFiles:\n${paths
        .map((p) => `- ${p}`)
        .join("\n")}\n`,
    );
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "raincast-app.zip";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded");
  };

  return (
    <div className="flex h-full bg-[#111118] overflow-hidden">
      <FileExplorer
        paths={paths}
        activePath={currentPath}
        onOpen={openFile}
        onSearch={setSearch}
        search={search}
      />
      <div className="flex-1 min-w-0 flex flex-col">
        <FilePathHeader
          path={currentPath}
          onCopy={copyCurrent}
          onDownload={downloadZip}
          onRegenerate={regenerate}
          canAct={paths.length > 0}
          isBuilding={isBuilding}
        />
        <FileTabs
          tabs={openTabs}
          active={currentPath}
          onSelect={setActiveFile}
          onClose={closeTab}
        />
        <div className="flex-1 min-h-0 bg-[#111118]">
          {currentPath ? (
            <Editor
              key={currentPath}
              height="100%"
              path={currentPath}
              language={langForPath(currentPath)}
              value={currentContent}
              theme="raincast-dark"
              beforeMount={defineRaincastTheme}
              onMount={(ed) => setEditorInstance(ed)}
              options={{
                readOnly: true,
                minimap: { enabled: false },
                fontFamily:
                  "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, monospace",
                fontSize: 13,
                lineHeight: 1.6 * 13,
                lineNumbers: "on",
                scrollBeyondLastLine: false,
                wordWrap: "off",
                padding: { top: 14, bottom: 14 },
                smoothScrolling: true,
                cursorSmoothCaretAnimation: "on",
                cursorBlinking: "smooth",
                renderLineHighlight: "all",
                scrollbar: {
                  vertical: "hidden",
                  horizontal: "hidden",
                  alwaysConsumeMouseWheel: false,
                  handleMouseWheel: true,
                },
                overviewRulerLanes: 0,
                guides: { indentation: true, highlightActiveIndentation: true },
                renderWhitespace: "none",
                contextmenu: false,
                folding: false,
              }}
            />
          ) : (
            <EmptyCodeState />
          )}
        </div>
      </div>
    </div>
  );
}

function EmptyCodeState() {
  return (
    <div className="h-full flex flex-col items-center justify-center text-center px-6">
      <div className="font-mono text-[10px] text-[#5a5a75] mb-3 tracking-[0.2em] uppercase">
        const App = () =&gt; …
      </div>
      <p className="font-display text-2xl text-[#c0c0d8] mb-1">Code</p>
      <p className="text-xs text-[#6b6b85] max-w-[280px]">
        Your generated source will stream here, organized into a clean folder
        structure based on what you're building.
      </p>
    </div>
  );
}
