import Editor from "@monaco-editor/react";
import { Code2, Copy, Download, RefreshCw, FileCode } from "lucide-react";
import JSZip from "jszip";
import { Button } from "@/components/ui/button";
import { useRaincastStore } from "@/store/raincastStore";
import { useAIBuild } from "@/hooks/useAIBuild";
import { toast } from "sonner";

export function CodeViewer() {
  const code = useRaincastStore((s) => s.currentCode);
  const isBuilding = useRaincastStore((s) => s.isBuilding);
  const { regenerate } = useAIBuild();

  const copy = async () => {
    if (!code) return;
    await navigator.clipboard.writeText(code);
    toast.success("Code copied");
  };

  const download = async () => {
    if (!code) return;
    const zip = new JSZip();
    zip.file("App.jsx", code);
    zip.file(
      "README.md",
      "# Generated by RAINCAST\n\nThis is a single-file React component. Open in any React project.\n",
    );
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "raincast-app.zip";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded");
  };

  return (
    <div className="flex flex-col h-full bg-panel">
      <div className="h-9 shrink-0 px-3 flex items-center border-b border-border text-xs uppercase tracking-wider text-muted-foreground font-medium">
        <Code2 className="w-3.5 h-3.5 mr-2 text-primary" />
        Code
        <span className="ml-2 normal-case tracking-normal text-foreground/70 flex items-center gap-1">
          <FileCode className="w-3 h-3" /> App.jsx
        </span>
        <div className="ml-auto flex gap-1">
          <Button
            size="sm"
            variant="ghost"
            className="h-7 text-xs"
            onClick={regenerate}
            disabled={isBuilding || !code}
          >
            <RefreshCw className="w-3.5 h-3.5 mr-1" />
            Regenerate
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 text-xs"
            onClick={copy}
            disabled={!code}
          >
            <Copy className="w-3.5 h-3.5 mr-1" />
            Copy
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-7 text-xs"
            onClick={download}
            disabled={!code}
          >
            <Download className="w-3.5 h-3.5 mr-1" />
            .zip
          </Button>
        </div>
      </div>

      <div className="flex-1 min-h-0">
        {code ? (
          <Editor
            height="100%"
            defaultLanguage="javascript"
            language="javascript"
            value={code}
            theme="vs-dark"
            options={{
              readOnly: true,
              minimap: { enabled: false },
              fontFamily: "JetBrains Mono, ui-monospace, monospace",
              fontSize: 13,
              lineNumbers: "on",
              scrollBeyondLastLine: false,
              wordWrap: "on",
              padding: { top: 12, bottom: 12 },
              smoothScrolling: true,
              renderLineHighlight: "none",
            }}
          />
        ) : (
          <div className="h-full flex items-center justify-center text-sm text-muted-foreground">
            Your generated code will appear here.
          </div>
        )}
      </div>
    </div>
  );
}
